- hosts: "all"

  handlers:
    - name: Install Docker Engine
      ansible.builtin.apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        update_cache: yes

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: 
         - curl
         - wget
         - zsh
         - vim
         - rsync
         - sudo
         - mc
         - htop
         - git
         - ca-certificates
         - wormhole
         - gnupg
         - lsb-release
        update_cache: yes

    - name: Create keyrings dir
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker repository key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
      notify: Install Docker Engine
